/* Ejemplos resueltos de los cursos que se rehacen con el equipo del alumno.
   «busca» es el texto exacto del curso en español (con los espacios normalizados); «por», la versión con el equipo del
   alumno. En las ediciones traducidas cada ejemplo va marcado en la página (data-tu-ej = su posición en esta lista) y
   se usa la plantilla de su idioma (en, fr, de, it, pt). Si al alumno le falta algún dato de la plantilla, se deja el
   ejemplo del curso tal cual.
   Variables: m_* (cielo profundo), p_* (paisaje con objetivo), pl_* (planetaria); ver personaliza.js. */
window.ASTRO_CURSOS_EJEMPLOS = [
  /* ── gran campo: paisaje con la K-1 II y el Irix ── */
  {busca: "La K-1 II con el Irix 15 mm cubre unos 100° × 77° (110° en diagonal).",
   por: "Tu {p_cam} con tu {p_obj} cubre unos {p_campo} ({p_diag} en diagonal).",
   en: "Your {p_cam} with your {p_obj} covers about {p_campo} ({p_diag} diagonally).",
   fr: "Votre {p_cam} avec votre {p_obj} couvre environ {p_campo} ({p_diag} en diagonale).",
   de: "Deine {p_cam} mit deinem {p_obj} deckt etwa {p_campo} ab ({p_diag} diagonal).",
   it: "La tua {p_cam} con il tuo {p_obj} copre circa {p_campo} ({p_diag} in diagonale).",
   pt: "A sua {p_cam} com a sua {p_obj} cobre cerca de {p_campo} ({p_diag} na diagonal)."},
  {busca: "Unos 16 s según la regla NPF con los píxeles de 4,88 µm de la K-1 II. La regla de los 500 daría 33 s, demasiado para estrellas puntuales.",
   por: "Con tu equipo, unos {p_npf} según la regla NPF con los píxeles de {p_pix} µm de tu {p_cam} y tu {p_obj} a f/{p_N}. La regla de los 500 daría {p_500}, demasiado para estrellas puntuales.", todas: true,
   en: "With your gear, about {p_npf} according to the NPF rule with the {p_pix} µm pixels of your {p_cam} and your {p_obj} at f/{p_N}. The 500 rule would give {p_500}, too long for pinpoint stars.",
   fr: "Avec votre matériel, environ {p_npf} selon la règle NPF, avec les pixels de {p_pix} µm de votre {p_cam} et votre {p_obj} à f/{p_N}. La règle des 500 donnerait {p_500}, trop pour des étoiles ponctuelles.",
   de: "Mit deiner Ausrüstung etwa {p_npf} nach der NPF-Regel mit den {p_pix}-µm-Pixeln deiner {p_cam} und deinem {p_obj} bei f/{p_N}. Die 500er-Regel ergäbe {p_500} – zu viel für punktförmige Sterne.",
   it: "Con la tua attrezzatura, circa {p_npf} secondo la regola NPF con i pixel da {p_pix} µm della tua {p_cam} e il tuo {p_obj} a f/{p_N}. La regola del 500 darebbe {p_500}, troppo per avere stelle puntiformi.",
   pt: "Com o seu equipamento, cerca de {p_npf}, segundo a regra NPF, com os píxeis de {p_pix} µm da sua {p_cam} e a sua {p_obj} a f/{p_N}. A regra dos 500 daria {p_500}, demasiado para estrelas pontuais."},
  {busca: "Con la completa, el Irix a f/2.8 y declinación −20° salen unos 8 s.",
   por: "Con la completa, tu {p_obj} a f/{p_N} y declinación −20° da unos {p_npf_full}.", todas: true,
   en: "With the full version, your {p_obj} at f/{p_N} and declination −20° gives about {p_npf_full}.",
   fr: "Avec la complète, votre {p_obj} à f/{p_N} et une déclinaison de −20°, on obtient environ {p_npf_full}.",
   de: "Mit der vollständigen ergeben sich für dein {p_obj} bei f/{p_N} und −20° Deklination etwa {p_npf_full}.",
   it: "Con la completa, con il tuo {p_obj} a f/{p_N} e declinazione −20° si ottengono circa {p_npf_full}.",
   pt: "Com a completa, a sua {p_obj} a f/{p_N} e declinação −20° dá cerca de {p_npf_full}."},
  {busca: "Con la K-1 II y el Irix 15 mm, Spot Stars dará valores cercanos a los del módulo 6: unos 15 o 16 s a f/2.4–f/2.8 con la precisión normal",
   por: "Con tu {p_cam} y tu {p_obj}, Spot Stars dará valores cercanos a los del módulo 6: unos {p_npf} a f/{p_N} con la precisión normal", todas: true,
   en: "With your {p_cam} and your {p_obj}, Spot Stars will give values close to those in module 6: around {p_npf} at f/{p_N} with normal accuracy",
   fr: "Avec votre {p_cam} et votre {p_obj}, Spot Stars donnera des valeurs proches de celles du module 6 : environ {p_npf} à f/{p_N} avec la précision normale",
   de: "Mit deiner {p_cam} und deinem {p_obj} liefert Spot Stars Werte nahe an denen aus Modul 6: etwa {p_npf} bei f/{p_N} mit normaler Genauigkeit",
   it: "Con la tua {p_cam} e il tuo {p_obj}, Spot Stars darà valori vicini a quelli del modulo 6: circa {p_npf} a f/{p_N} con la precisione normale",
   pt: "Com a sua {p_cam} e a sua {p_obj}, o Spot Stars dará valores próximos dos do módulo 6: cerca de {p_npf} a f/{p_N} com a precisão normal"},
  {busca: "Exposición: la de Spot Stars (unos 15 s a f/2.8 con el Irix).",
   por: "Exposición: la de Spot Stars (unos {p_npf} a f/{p_N} con tu {p_obj}).", todas: true,
   en: "Exposure: the Spot Stars value (about {p_npf} at f/{p_N} with your {p_obj}).",
   fr: "Temps de pose : celui de Spot Stars (environ {p_npf} à f/{p_N} avec votre {p_obj}).",
   de: "Belichtungszeit: die von Spot Stars (etwa {p_npf} bei f/{p_N} mit deinem {p_obj}).",
   it: "Esposizione: quella di Spot Stars (circa {p_npf} a f/{p_N} con il tuo {p_obj}).",
   pt: "Exposição: a do Spot Stars (cerca de {p_npf} a f/{p_N} com a sua {p_obj})."},
  {busca: "Con el Irix en vertical (77° de ancho), giros de unos 40° dan un solape holgado.",
   por: "Con tu {p_obj} en vertical ({p_campoH}° de ancho), giros de unos {p_giro}° dan un solape holgado.", todas: true,
   en: "With your {p_obj} in portrait ({p_campoH}° wide), rotating about {p_giro}° each time gives a generous overlap.",
   fr: "Avec votre {p_obj} en vertical ({p_campoH}° de large), des rotations d’environ {p_giro}° donnent un recouvrement confortable.",
   de: "Mit deinem {p_obj} im Hochformat ({p_campoH}° breit) ergeben Drehungen um etwa {p_giro}° eine großzügige Überlappung.",
   it: "Con il tuo {p_obj} in verticale ({p_campoH}° di larghezza), rotazioni di circa {p_giro}° danno una sovrapposizione abbondante.",
   pt: "Com a sua {p_obj} na vertical ({p_campoH}° de largura), rotações de cerca de {p_giro}° dão uma sobreposição folgada."},
  {busca: "Con el Irix a f/2.8, unos 16 s según la regla NPF simplificada; la completa, más estricta, pide la mitad.",
   por: "Con tu {p_obj} a f/{p_N}, unos {p_npf} según la regla NPF simplificada; la completa, más estricta, a −20° pide unos {p_npf_full}.", todas: true,
   en: "With your {p_obj} at f/{p_N}, about {p_npf} according to the simplified NPF rule; the full rule, which is stricter, calls for about {p_npf_full} at −20°.",
   fr: "Avec votre {p_obj} à f/{p_N}, environ {p_npf} selon la règle NPF simplifiée ; la règle complète, plus stricte, demande environ {p_npf_full} à −20°.",
   de: "Mit deinem {p_obj} bei f/{p_N} etwa {p_npf} nach der vereinfachten NPF-Regel; die vollständige, strengere Formel verlangt bei −20° etwa {p_npf_full}.",
   it: "Con il tuo {p_obj} a f/{p_N}, circa {p_npf} secondo la regola NPF semplificata; quella completa, più severa, a −20° chiede circa {p_npf_full}.",
   pt: "Com a sua {p_obj} a f/{p_N}, cerca de {p_npf} segundo a regra NPF simplificada; a completa, mais exigente, a −20° pede cerca de {p_npf_full}."},
  {busca: "Con un 15 mm en trípode, un viento moderado se tolera; con el SV555 a 243 mm, no.",
   por: "Con tu {p_obj} en trípode, un viento moderado se tolera; con tu {m_tel} a {m_F} mm, mucho menos.", todas: true,
   en: "With your {p_obj} on a tripod, a moderate wind is tolerable; with your {m_tel} at {m_F} mm, far less so.",
   fr: "Avec votre {p_obj} sur trépied, un vent modéré se tolère ; avec votre {m_tel} à {m_F} mm, beaucoup moins.",
   de: "Mit deinem {p_obj} auf dem Stativ ist mäßiger Wind noch vertretbar; mit deinem {m_tel} bei {m_F} mm viel weniger.",
   it: "Con il tuo {p_obj} su treppiede, un vento moderato si tollera; con il tuo {m_tel} a {m_F} mm, molto meno.",
   pt: "Com a sua {p_obj} em tripé, um vento moderado tolera-se; com o seu {m_tel} a {m_F} mm, muito menos."},

  /* ── gran campo: cielo profundo con el SV555 ── */
  {busca: "Encuadre: con la 2600MC y el SV555 caben las dos nebulosas juntas en los 5,5° × 3,7° del campo.",
   por: "Encuadre: con tu {m_cam} y tu {m_tel} el campo es de {m_campo}: {m_corazon_alma}.", todas: true,
   en: "Framing: with your {m_cam} and your {m_tel} the field is {m_campo}: {m_corazon_alma}.",
   fr: "Cadrage : avec votre {m_cam} et votre {m_tel}, le champ fait {m_campo} : {m_corazon_alma}.",
   de: "Bildausschnitt: Mit deiner {m_cam} und deinem {m_tel} ist das Bildfeld {m_campo} groß: {m_corazon_alma}.",
   it: "Inquadratura: con la tua {m_cam} e il tuo {m_tel} il campo è di {m_campo}: {m_corazon_alma}.",
   pt: "Enquadramento: com a sua {m_cam} e o seu {m_tel}, o campo é de {m_campo}: {m_corazon_alma}."},
  {busca: "Focal de guiado: 243 mm, la del SV555, porque el OAG usa su luz.",
   por: "Focal de guiado con OAG: {m_F} mm, la de tu {m_tel}, porque el OAG usa su luz.", todas: true,
   en: "Guide focal length with an OAG: {m_F} mm, that of your {m_tel}, because the OAG uses its light.",
   fr: "Focale de guidage avec OAG : {m_F} mm, celle de votre {m_tel}, car l’OAG utilise sa lumière.",
   de: "Guiding-Brennweite mit OAG: {m_F} mm, die deines {m_tel}, weil der OAG dessen Licht nutzt.",
   it: "Focale di guida con OAG: {m_F} mm, quella del tuo {m_tel}, perché l’OAG usa la sua luce.",
   pt: "Distância focal de guiagem com OAG: {m_F} mm, a do seu {m_tel}, porque o OAG usa a sua luz."},

  /* ── planetaria: el caso práctico de Júpiter ── */
  {busca: "Schmidt-Cassegrain de 235 mm, f/10, focal nativa 2.350 mm",
   por: "{pl_tel}: {pl_D} mm, f/{pl_fr}, focal nativa {pl_F} mm", todas: true,
   en: "{pl_tel}: {pl_D} mm, f/{pl_fr}, native focal length {pl_F} mm",
   fr: "{pl_tel} : {pl_D} mm, f/{pl_fr}, focale native {pl_F} mm",
   de: "{pl_tel}: {pl_D} mm, f/{pl_fr}, native Brennweite {pl_F} mm",
   it: "{pl_tel}: {pl_D} mm, f/{pl_fr}, focale nativa {pl_F} mm",
   pt: "{pl_tel}: {pl_D} mm, f/{pl_fr}, distância focal nativa de {pl_F} mm"},
  {busca: "Planetaria color, píxel de 2,9 µm",
   por: "{pl_cam}, {pl_color}, píxel de {pl_pix} µm", todas: true,
   en: "{pl_cam}, {pl_color}, {pl_pix} µm pixels",
   fr: "{pl_cam}, {pl_color}, pixels de {pl_pix} µm",
   de: "{pl_cam}, {pl_color}, Pixelgröße {pl_pix} µm",
   it: "{pl_cam}, {pl_color}, pixel da {pl_pix} µm",
   pt: "{pl_cam}, {pl_color}, píxel de {pl_pix} µm"},
  {busca: "ADC, rueda con filtro de corte UV/IR, cámara; sin barlow",
   por: "ADC, rueda con filtro de corte UV/IR, cámara; {pl_barlow_txt}", todas: true,
   en: "ADC, filter wheel with UV/IR-cut filter, camera; {pl_barlow_txt}",
   fr: "ADC, roue à filtres avec filtre UV/IR-cut, caméra ; {pl_barlow_txt}",
   de: "ADC, Filterrad mit UV/IR-Sperrfilter, Kamera; {pl_barlow_txt}",
   it: "ADC, ruota con filtro UV/IR cut, camera; {pl_barlow_txt}",
   pt: "ADC, roda com filtro de corte UV/IR, câmara; {pl_barlow_txt}"},
  {busca: "Muestreo: con píxel de 2,9 µm, el rango práctico es de f/10 a f/14,5 y Nyquist a 550 nm pide f/10,5. A foco directo, el SCT trabaja a f/10: justo en el límite bajo. Decisión: sin barlow con seeing normal, y una barlow de 1,3× a 1,4× preparada por si la noche es excelente.",
   por: "Muestreo: con píxel de {pl_pix} µm, el rango práctico es de f/{pl_lo} a f/{pl_hi} y Nyquist a 550 nm pide f/{pl_nyq}. A foco directo, tu {pl_tel} trabaja a f/{pl_fr}: {pl_estado}. Decisión: {pl_decision}.", todas: true,
   en: "Sampling: with {pl_pix} µm pixels, the practical range is f/{pl_lo} to f/{pl_hi}, and Nyquist at 550 nm calls for f/{pl_nyq}. At prime focus, your {pl_tel} works at f/{pl_fr}: {pl_estado}. Decision: {pl_decision}.",
   fr: "Échantillonnage : avec des pixels de {pl_pix} µm, la plage pratique va de f/{pl_lo} à f/{pl_hi}, et Nyquist à 550 nm demande f/{pl_nyq}. Au foyer direct, votre {pl_tel} travaille à f/{pl_fr} : {pl_estado}. Décision : {pl_decision}.",
   de: "Abtastung: Bei {pl_pix} µm Pixelgröße reicht der praxistaugliche Bereich von f/{pl_lo} bis f/{pl_hi}, und Nyquist bei 550 nm verlangt f/{pl_nyq}. Im Primärfokus arbeitet dein {pl_tel} mit f/{pl_fr}: {pl_estado}. Entscheidung: {pl_decision}.",
   it: "Campionamento: con pixel da {pl_pix} µm, l’intervallo pratico va da f/{pl_lo} a f/{pl_hi} e Nyquist a 550 nm richiede f/{pl_nyq}. A fuoco diretto, il tuo {pl_tel} lavora a f/{pl_fr}: {pl_estado}. Decisione: {pl_decision}.",
   pt: "Amostragem: com píxel de {pl_pix} µm, o intervalo prático vai de f/{pl_lo} a f/{pl_hi} e Nyquist a 550 nm pede f/{pl_nyq}. Em foco primário, o seu {pl_tel} trabalha a f/{pl_fr}: {pl_estado}. Decisão: {pl_decision}."},
  {busca: "Rotación: Dawes para 235 mm es 0,49″. Con Júpiter de 45″, el tiempo máximo es de unos 63 s. Decisión: vídeos de 60 s y derrotación en grupos.",
   por: "Rotación: Dawes para tu {pl_tel} de {pl_D} mm es {pl_dawes}″. Con Júpiter de 45″, el tiempo máximo es de unos {pl_tjup}. Decisión: vídeos de {pl_video} y derrotación en grupos.", todas: true,
   en: "Rotation: the Dawes limit for your {pl_D} mm {pl_tel} is {pl_dawes}″. With Jupiter at 45″, the maximum time is about {pl_tjup}. Decision: {pl_video} videos and derotation in groups.",
   fr: "Rotation : la limite de Dawes de votre {pl_tel} de {pl_D} mm est de {pl_dawes}″. Avec un Jupiter de 45″, la durée maximale est d’environ {pl_tjup}. Décision : vidéos de {pl_video} et dérotation par groupes.",
   de: "Rotation: Die Dawes-Grenze deines {pl_tel} mit {pl_D} mm liegt bei {pl_dawes}″. Bei einem Jupiter von 45″ beträgt die maximale Aufnahmedauer etwa {pl_tjup}. Entscheidung: Videos von {pl_video} und Derotation in Gruppen.",
   it: "Rotazione: il limite di Dawes del tuo {pl_tel} da {pl_D} mm è {pl_dawes}″. Con Giove a 45″, il tempo massimo è di circa {pl_tjup}. Decisione: video da {pl_video} e derotazione a gruppi.",
   pt: "Rotação: o limite de Dawes do seu {pl_tel} de {pl_D} mm é de {pl_dawes}″. Com Júpiter a 45″, o tempo máximo é de cerca de {pl_tjup}. Decisão: vídeos de {pl_video} e derrotação por grupos."}
];
